version: "3"

services:
  redis:
    image: redis:5.0
    ports:
      - 6379:6379

  mysql:
    image: mysql:latest
    ports:
      - ${MYSQL_PORT}:3306
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    ports:
      - 127.0.0.1:3000:8080
    environment:
      SWAGGER_JSON: /api/api-document.yaml
    volumes:
      - ./api-document.yaml:/api/api-document.yaml:ro

volumes:
  db-data:
    driver: local
