version: "3"

services:
  redis:
    image: redis:5.0
    ports:
      - 6379:6379

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"  # パスワードなしでログイン可能にします
      MYSQL_DATABASE: game
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db-data:/var/lib/mysql
      - $PWD/_tools/mysql/conf.d:/etc/mysql/conf.d:cached
    ports:
      - 3306:3306

  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    ports:
      - 127.0.0.1:3000:8080
    environment:
      SWAGGER_JSON: /api/api-document.yaml
    volumes:
      - ./api-document.yaml:/api/api-document.yaml:ro

volumes:
  db-data:
